# Spring配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.6.100.89:3307/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: XXyf131468*

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.ruoyi.domain
  configuration:
    mapUnderscoreToCamelCase: true

# 日志配置
logging:
  level:
    com.ruoyi.question: debug

# 项目相关配置
ruoyi:
  # 文件上传路径
  profile: ./question/uploadPath
